### ISSUE TITLE
02.212TS The Visual Culture of Science and Technology notes

### ISSUE THREAD

**Issue by software312** [OpenSUTD/course-notes#15]
Hi, I would like to contribute my notes for this course

Gdocs link: https://drive.google.com/drive/folders/1u1rmAY2QNQsIdLC4710D2zQT1_L-tA-N?usp=sharing

**Comment by flamanta** [comment]
Hi software312,

Could you provide me with your name so that you can be credited for your contributions?

Thank you. 😄

**Comment by lyqht** [comment]
hi @flamanta , the notes are written by: Tan Tiang Teck (@software312 ) and me! 
thank you 😄
